# This is the dev-rapid topic.
# Add your application to the ACL structure to gain read or write access based on your needs.
#
# Two topics will be created, one for development and one for production.

---
apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: dev-rapid
  namespace: aura
  labels:
    team: aura
spec:
  pool: {{ pool }}
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 2
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: {{ retention_hours }}
  acl:
    - team: nais-system
      application: naiserator
      access: write
    - team: nais
      application: naiserator
      access: write
    - team: aura
      application: fasit
      access: write
    - team: nais-analyse
      application: devrapid-git-push
      access: write
    - team: nais-system
      application: deployment-event-relays
      access: read
    - team: nais-analyse
      application: devrapid-leadtime
      access: read
    - access: read
      team: nais-analyse
      application: deploy-dataproduct
